# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-08 05:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TwitterTracks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(default='', max_length=255)),
                ('user', models.ManyToManyField(db_table='twitter_track_xref_user', related_name='tw_tracks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'twitter_tracks',
                'ordering': ('text',),
            },
        ),
    ]
