# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-23 17:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tweets', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='twittermention',
            options={'ordering': ('name',)},
        ),
        migrations.AddField(
            model_name='twittermention',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
