# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-23 17:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0002_auto_20160223_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twittermention',
            name='user',
            field=models.ManyToManyField(db_table='twitter_mention_xref_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
